services:
  mavros:
    image: mavros_l4t:latest
    container_name: mavros
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - ROS_DOMAIN_ID=0
      - GCS_IP=192.168.127.1